#DATABASE CONNECTION
spring:
  datasource:  
     url:  jdbc:mysql://localhost:3306/backend_project
     username:  root
     password:  password
  jpa:
    hibernate:
      ddl-auto: update

#SWAGGER CONFIG
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
